env:
    # Config
    CONFIG: config.sh

    # Telegram
    TG_CHAT_ID: ENCRYPTED[399b06125708cabba5658c52ef69e34e1441496958aa7dbc90791323bcd4e75a3a062dc6c4d56be38a98fb21bd9879bc]
    TG_TOKEN: ENCRYPTED[789e7b7b2530a4ce43aea7685d0ad4758c3e5a17f1c7b2fb69ed92ec31a9368f38c66aad19783ee5a87847d6320c2bae]

    # Cirrus Specific Vars (Do *NOT* Change)
    CIRRUS_SHELL: bash

task:
  name: "Recovery Build"
  timeout_in: 120m
  container:
      image: ghcr.io/sushrut1101/docker:arch
      cpu: 8
      memory: 20G

  Checks_script:
      - bash -c "$(curl -sL https://raw.githubusercontent.com/Nico170420/SkyHawk-CI/sh/scripts/checks.sh)"

  Sync_script:
      - bash -c "$(curl -sL https://raw.githubusercontent.com/Nico170420/SkyHawk-CI/sh/scripts/sync.sh)"

  Build_script:
      - bash -c "$(curl -sL https://raw.githubusercontent.com/Nico170420/SkyHawk-CI/sh/scripts/build.sh)"

  Upload_script:
      - export TIMEOUT=43200 # Link timeout (in minutes)
      - bash -c "$(curl -sL https://raw.githubusercontent.com/Nico170420/SkyHawk-CI/sh/scripts/upload.sh)"
